# Generated by Django 4.2.1 on 2024-09-18 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nexusback', '0002_messenger'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='messenger',
            options={'verbose_name': 'Messenger', 'verbose_name_plural': 'Messengers'},
        ),
    ]
