# Generated by Django 5.0.7 on 2024-09-24 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nexusback', '0004_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(default='', max_length=100, verbose_name='password'),
        ),
    ]
