# Generated by Django 5.0.7 on 2024-11-20 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nexusback', '0005_user_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='contain_files',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='message',
            name='message_id',
            field=models.CharField(default='', max_length=100, null=True, verbose_name='message id'),
        ),
    ]
