# Generated by Django 5.0.7 on 2024-12-09 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nexusback', '0007_imagemessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.CharField(default='', max_length=100, null=True, verbose_name='message id')),
                ('document', models.FileField(upload_to='uploads/')),
            ],
            options={
                'verbose_name': 'Document',
                'verbose_name_plural': 'Documents',
            },
        ),
    ]
