# Generated by Django 5.0.7 on 2024-12-30 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nexusback', '0008_documentmessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='', max_length=100, null=True, verbose_name='password'),
        ),
    ]
