# Generated by Django 5.0.7 on 2025-01-30 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nexusback', '0009_alter_user_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.CharField(default='', max_length=100, null=True, verbose_name='message id')),
                ('video', models.FileField(upload_to='videos/')),
            ],
            options={
                'verbose_name': 'Video',
                'verbose_name_plural': 'Videos',
            },
        ),
    ]
