# Generated by Django 5.0.7 on 2025-02-13 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nexusback', '0010_videomessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=10, verbose_name='Login')),
                ('first_name', models.CharField(max_length=30, verbose_name='name')),
                ('last_name', models.CharField(max_length=30, verbose_name='surname')),
                ('date_birthday', models.DateTimeField(auto_now_add=True)),
                ('country', models.CharField(max_length=100, verbose_name='country')),
                ('email', models.CharField(max_length=100, verbose_name='mail')),
                ('phone', models.CharField(max_length=14, verbose_name='phone')),
                ('description', models.TextField(max_length=500, verbose_name='descript')),
            ],
            options={
                'verbose_name': 'Aplication',
                'verbose_name_plural': 'Aplications',
            },
        ),
    ]
