# Generated by Django 5.0.7 on 2025-02-13 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nexusback', '0011_application'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='status',
            field=models.CharField(default='onCheck', max_length=100, null=True, verbose_name='status'),
        ),
    ]
