# Generated by Django 5.0.7 on 2025-02-16 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nexusback', '0012_application_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='access_token',
            field=models.TextField(max_length=100, null=True, verbose_name='accessToken'),
        ),
    ]
