from django.urls import path
from . import  views


urlpatterns = [
    path('<int:key>/', views.main, name='main'),
    path('getData/', views.getData, name="getData"),
    path('authToken/', views.authToken, name = 'authToken'),
    path('getUsers/', views.getUsers, name="getUsers"),
    path('getChat/<int:key>/', views.getYourChat, name="getChat"),
    path('createChat/<int:key>/', views.createChat, name="createChat"),
    path('getCompanion/<int:key>/', views.getCompanion, name="Companion"),
    path('addMessage/<int:key>/', views.addMessage, name="addMessage"),
    path('getMessage/<int:key>/', views.getMessage, name="getMessage"),
    path('setUserImg/<int:key>/', views.setUserImg, name="setUserImg"),
    path('getStatisticMessage/<int:key>/', views.getStatisticMessage, name="getStatistic"),
    path('getLastMess/<int:key>/', views.getLastMess, name = "getLastMess"),
    path('getMessageImage/<int:messageId>/', views.getImages, name="getImages"),
    path('getDocuments/<int:messageId>/', views.getDocuments, name = "getDocuments"),
    path('getVideos/<int:messageId>/', views.getVideos, name = "getVideos"),
    path('uploadImageMessage/<int:key>/', views.uploadImageMessage, name = "uploadImageMessage"),
    path('getCountMessages/<int:key>/', views.getCountMessages, name = "getCountMessages"),
    path('topUsers/', views.TopUsers, name="topUsers"),
    path('getPhoto/<int:key>/', views.getPhoto, name="getPhoto"),
    path('changeData/<int:key>/', views.changeData, name = 'changeData'),
    path('ChangePassword/<int:key>/', views.ChangePassword, name ='ChangePassword'),
    path('confirmCode/<int:key>/', views.ConfirmCode, name = "confirm"),
    path('deleteChat/<int:key>/', views.DeleteChat, name='deleteChat'),
    path('deleteChatHistory/<int:key>/', views.DeleteChatHistory, name='deleteChatHistory'),
    path('getYourChatsMessages/<int:key>/', views.GetYourChatMessages, name="getChatMessages"),
    path('checkApplication/', views.CheckApplications, name='CheckApplications'),
    path('createApplication/', views.CreateApplications, name ='createApplic'),
    path('getApplications/<str:key>/', views.getApplications, name = 'getApplications'),
    path('approveApplic/', views.approveApplic, name = 'approveApplic'),
    path('denyApplic/', views.denyApplic, name = "denyApplic"),
    path('get_csrf_token/', views.get_csrf_token, name='get_csrf'),
    path('getMedia/<int:key>/', views.getAllMedia, name="getAllMedia"),
    path('getMediaDocs/<int:key>/', views.getAllMediaDocs, name="getAllMediaDocs"),
]
