# Generated by Django 4.2.1 on 2024-09-18 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=100, verbose_name='user_id')),
                ('user_name', models.CharField(max_length=100, verbose_name='user name')),
                ('user_first_name', models.CharField(max_length=100, verbose_name='user first_name')),
                ('user_last_name', models.CharField(max_length=100, verbose_name='user last_name')),
                ('user_date_birth', models.DateField(verbose_name='user_date_birth')),
                ('user_descript', models.CharField(default="I'm busy", max_length=100, verbose_name='user description')),
                ('user_mail', models.CharField(default='', max_length=100, verbose_name='user mail')),
                ('user_phone', models.CharField(max_length=12, verbose_name='phone')),
                ('user_img', models.ImageField(blank=True, default='images/user.png', null=True, upload_to='images/')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
            },
        ),
    ]
